/**: # HH_240410
  ros__parameters:
    filter_target_label:
      UNKNOWN : true
      CAR : true
      TRUCK : true
      BUS : true
      TRAILER : true
      MOTORCYCLE : true
      BICYCLE : true
      PEDESTRIAN : true

    upper_bound_x: 100.0
    lower_bound_x: 0.0
    upper_bound_y: 10.0
    lower_bound_y: -10.0
