/**:
  ros__parameters:
    # HH_240407
    # Latitude of local origin
    latitude: 360965.999225

    # Longitude of local origin
    longitude: 4065972.492659

    # Altitude of local origin
    altitude: 100.878965

    # # Latitude of local origin
    # latitude: 36.62467777325

    # # Longitude of local origin
    # longitude: 127.45688057965

    # # Altitude of local origin
    # altitude: 66.0728

    # Latitude of local origin
    # latitude: 36.729292

    # Longitude of local origin
    # longitude: 127.442958

    # Altitude of local origin
    # altitude: 66.0728
