# this file is PCD Map offset information

 /**: # HH_240320 # C-track
   ros__parameters:
     map_origin:
       latitude: 36.72929210
       longitude: 127.44295773
       elevation: 100.878965
       roll: 0.0
       pitch: 0.0
       yaw: 0.0

#/**: # HH_240320 # CBNU
#  ros__parameters:
#    map_origin:
#      latitude: 36.62438409
#      longitude: 127.45583925
#      elevation: 86.641012
#      roll: 0.0
#      pitch: 0.0
#      yaw: 0.0

# /**: # HH_240320 # CN_OEIS
#   ros__parameters:
#     map_origin:
#       latitude: 36.74975088
#       longitude: 126.99075433
#       elevation: 54.607800
#       roll: 0.0
#       pitch: 0.0
#       yaw: 0.0

# /**: # HH_240320 # 52SCF
#   ros__parameters:
#     map_origin:
#       latitude: 36.12409583213699
#       longitude: 126.77760861456342
#       elevation: 86.641012
#       roll: 0.0
#       pitch: 0.0
#       yaw: 0.0

