# HH_250206
/**:
  ros__parameters:
    wheel_radius: 0.4064 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.205 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 3.0 # between front wheel center and rear wheel center
    wheel_tread: 1.563 # between left wheel center and right wheel center
    front_overhang: 1.185 # +0.3 # between front wheel center and vehicle front
    rear_overhang: 1.585 # +0.2 # between rear wheel center and vehicle rear
    left_overhang: 0.1785 # +0.03 # between left wheel center and vehicle left
    right_overhang: 0.1785 # +0.03 # between right wheel center and vehicle right
    vehicle_height: 1.75 # +0.3
    max_steer_angle: 0.70 # [rad] 
